from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(361, 588)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.Output_label = QtWidgets.QLabel(self.centralwidget)
        self.Output_label.setGeometry(QtCore.QRect(10, 10, 341, 81))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.Output_label.setFont(font) 
        self.Output_label.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.Output_label.setMouseTracking(False)
        self.Output_label.setFrameShape(QtWidgets.QFrame.Box)
        self.Output_label.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Output_label.setLineWidth(5)
        self.Output_label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.Output_label.setObjectName("Output_label")
        self.percentbutton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("Coming soon, type"))
        self.percentbutton.setGeometry(QtCore.QRect(20, 110, 64, 65))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.percentbutton.setFont(font)
        self.percentbutton.setObjectName("percentbutton")
        self.cbutton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("C"))
        self.cbutton.setGeometry(QtCore.QRect(100, 110, 64, 65))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.cbutton.setFont(font)
        self.cbutton.setObjectName("cbutton")
        self.arrowbutton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.arrow())
        self.arrowbutton.setGeometry(QtCore.QRect(190, 110, 64, 65))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.arrowbutton.setFont(font)
        self.arrowbutton.setObjectName("arrowbutton")
        self.slashbutton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("/"))
        self.slashbutton.setGeometry(QtCore.QRect(270, 110, 64, 65))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.slashbutton.setFont(font)
        self.slashbutton.setObjectName("slashbutton")
        self.sevebutton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("7"))
        self.sevebutton.setGeometry(QtCore.QRect(20, 190, 64, 65))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.sevebutton.setFont(font)
        self.sevebutton.setObjectName("sevebutton")
        self.multiplybutton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("*"))
        self.multiplybutton.setGeometry(QtCore.QRect(270, 190, 64, 65))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.multiplybutton.setFont(font)
        self.multiplybutton.setObjectName("multiplybutton")
        self.eightbutton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("8"))
        self.eightbutton.setGeometry(QtCore.QRect(100, 190, 64, 65))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.eightbutton.setFont(font)
        self.eightbutton.setObjectName("eightbutton")
        self.ninebutton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("9"))
        self.ninebutton.setGeometry(QtCore.QRect(190, 190, 64, 65))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.ninebutton.setFont(font)
        self.ninebutton.setObjectName("ninebutton")
        self.fourbutton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("4"))
        self.fourbutton.setGeometry(QtCore.QRect(20, 270, 64, 65))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.fourbutton.setFont(font)
        self.fourbutton.setObjectName("fourbutton")
        self.minusbutton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("-"))
        self.minusbutton.setGeometry(QtCore.QRect(270, 270, 64, 65))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.minusbutton.setFont(font)
        self.minusbutton.setObjectName("minusbutton")
        self.fivebutton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("5"))
        self.fivebutton.setGeometry(QtCore.QRect(100, 270, 64, 65))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.fivebutton.setFont(font)
        self.fivebutton.setObjectName("fivebutton")
        self.sixbutton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("6"))
        self.sixbutton.setGeometry(QtCore.QRect(190, 270, 64, 65))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.sixbutton.setFont(font)
        self.sixbutton.setObjectName("sixbutton")
        self.onebutton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("1"))
        self.onebutton.setGeometry(QtCore.QRect(20, 350, 64, 65))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.onebutton.setFont(font)
        self.onebutton.setObjectName("onebutton")
        self.addbutton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("+"))
        self.addbutton.setGeometry(QtCore.QRect(270, 350, 64, 65))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.addbutton.setFont(font)
        self.addbutton.setObjectName("addbutton")
        self.twobutton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("2"))
        self.twobutton.setGeometry(QtCore.QRect(100, 350, 64, 65))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.twobutton.setFont(font)
        self.twobutton.setObjectName("twobutton")
        self.threebutton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("3"))
        self.threebutton.setGeometry(QtCore.QRect(190, 350, 64, 65))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.threebutton.setFont(font)
        self.threebutton.setObjectName("threebutton")
        self.pointbutton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.dot_it())
        self.pointbutton.setGeometry(QtCore.QRect(190, 430, 64, 65))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.pointbutton.setFont(font)
        self.pointbutton.setObjectName("pointbutton")
        self.equaltobutton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.math_it())
        self.equaltobutton.setGeometry(QtCore.QRect(270, 430, 64, 65))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.equaltobutton.setFont(font)
        self.equaltobutton.setObjectName("equaltobutton")
        self.addsubbutton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.plus_minus())
        self.addsubbutton.setGeometry(QtCore.QRect(20, 430, 64, 65))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.addsubbutton.setFont(font)
        self.addsubbutton.setObjectName("addsubbutton")
        self.serobutton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("0"))
        self.serobutton.setGeometry(QtCore.QRect(100, 430, 64, 65))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.serobutton.setFont(font)
        self.serobutton.setObjectName("serobutton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 361, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    
    def math_it(self):
        screen = self.Output_label.text()
        try:
            #do the math
            answer = eval(screen)
            #change the output screen into answer
            self.Output_label.setText(str(answer))
        except:
            #output error to the screen
            self.Output_label.setText("ERROR")


    def plus_minus(self):
        screen = self.Output_label.text()
        if "-" in screen:
            self.Output_label.setText(screen.replace("-"," "))# we can use [screen= "-"+screen]
        else:
            self.Output_label.setText(f'-{screen}')

    def arrow(self):
        screen= self.Output_label.text()

        screen = screen[:-1]

        self.Output_label.setText(screen)

    #add a decimal in the output button
    def dot_it(self):
        screen = self.Output_label.text()
        if "." in screen:
            pass
        else:
            self.Output_label.setText(f"{screen}.")
    def press_it(self, pressed):
        if pressed== "C":
            self.Output_label.setText("0")
        else:
            #check to see if starts with 0 and delete 0
            if self.Output_label.text() =="0":
                self.Output_label.setText(" ")
            # concatenate the pressed button with what was there already
            self.Output_label.setText(f"{self.Output_label.text()}{pressed}")
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculator"))
        self.Output_label.setText(_translate("MainWindow", "0"))
        self.percentbutton.setText(_translate("MainWindow", "%"))
        self.cbutton.setText(_translate("MainWindow", "C"))
        self.arrowbutton.setText(_translate("MainWindow", "<<"))
        self.slashbutton.setText(_translate("MainWindow", "/"))
        self.sevebutton.setText(_translate("MainWindow", "7"))
        self.multiplybutton.setText(_translate("MainWindow", "x"))
        self.eightbutton.setText(_translate("MainWindow", "8"))
        self.ninebutton.setText(_translate("MainWindow", "9"))
        self.fourbutton.setText(_translate("MainWindow", "4"))
        self.minusbutton.setText(_translate("MainWindow", "-"))
        self.fivebutton.setText(_translate("MainWindow", "5"))
        self.sixbutton.setText(_translate("MainWindow", "6"))
        self.onebutton.setText(_translate("MainWindow", "1"))
        self.addbutton.setText(_translate("MainWindow", "+"))
        self.twobutton.setText(_translate("MainWindow", "2"))
        self.threebutton.setText(_translate("MainWindow", "3"))
        self.pointbutton.setText(_translate("MainWindow", "."))
        self.equaltobutton.setText(_translate("MainWindow", "="))
        self.addsubbutton.setText(_translate("MainWindow", "+/-"))
        self.serobutton.setText(_translate("MainWindow", "0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
